name: Run tests

on: [push, pull_request]

jobs:
  run-tests:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [2.7]
        include:
        - os: windows-latest
          os-name: w32
          pip-cache-path: ~\AppData\Local\pip\Cache

    name: Python ${{ matrix.python-version }} @ ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps:

      # Setup Python/pip
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip-cache-path }}
          key: ${{ runner.os }}-pip

      # Setup tox
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade "pip<21.0" "setuptools<45" wheel
          pip --version
          pip install --upgrade virtualenv tox
      - name: Set TOXENV
        run: |
          import os, sys
          pyver = '%d%d' % tuple(sys.version_info[:2])
          toxenv = 'py%s' % pyver
          if os.name == 'posix':
            toxenv += ',py%s-flake8' % pyver
          with open(os.environ['GITHUB_ENV'], 'a') as f:
            f.write('PYTHON_VERSION='
            + '.'.join(str(v) for v in sys.version_info[:2])
            + '\n')  # For run_with_env.cmd
            f.write('TOXENV=' + toxenv + '\n')
          print(toxenv)
        shell: python

      - name: Run tox @ w64
        run: |
          devscripts\CI\run_with_env.cmd tox -vvv
        shell: cmd
        if: ${{ runner.os == 'Windows' }}
